# Generated by Django 3.0.8 on 2020-08-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_StarYoutuber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField()),
                ('check_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'channel_views',
                'managed': False,
            },
        ),
    ]
