# Generated by Django 3.0.8 on 2020-08-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_StarYoutuber', '0002_channelviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoKeywordNew',
            fields=[
                ('keyword', models.CharField(max_length=100)),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'video_keyword_new',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='VideoKeyword',
        ),
    ]
