# Generated by Django 3.0.8 on 2020-08-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_id', models.CharField(max_length=200)),
                ('channel_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('channel_start_date', models.DateField(blank=True, null=True)),
                ('processed', models.BooleanField(blank=True, null=True)),
                ('upload_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('hidden_subscriber', models.BooleanField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('temp', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=500)),
                ('video_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('upload_time', models.DateTimeField()),
                ('processed', models.BooleanField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail_processed', models.BooleanField(blank=True, null=True)),
                ('forbidden', models.BooleanField(blank=True, null=True)),
                ('popularity', models.FloatField()),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoKeywordNew',
            fields=[
                ('keyword', models.CharField(max_length=100)),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'video_keyword_new',
                'managed': False,
            },
        ),
    ]
