# Generated by Django 3.0.8 on 2020-08-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('channel_id', models.CharField(max_length=200)),
                ('channel_description', models.CharField(blank=True, max_length=3000, null=True)),
                ('channel_start_date', models.DateField(blank=True, null=True)),
                ('processed', models.BooleanField(blank=True, null=True)),
                ('upload_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('hidden_subscriber', models.BooleanField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('temp', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channel',
                'managed': False,
            },
        ),
    ]
