# Generated by Django 3.0.8 on 2020-08-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Keyword', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('video_name', models.CharField(max_length=500)),
                ('video_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('video_id', models.CharField(max_length=100, unique=True)),
                ('upload_time', models.DateTimeField()),
                ('processed', models.BooleanField(blank=True, null=True)),
                ('thumbnail_url', models.CharField(blank=True, max_length=200, null=True)),
                ('thumbnail_processed', models.BooleanField(blank=True, null=True)),
                ('forbidden', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoKeywordNew',
            fields=[
                ('keyword', models.CharField(max_length=100)),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'video_keyword',
                'managed': False,
            },
        ),
    ]
