# Generated by Django 3.0.8 on 2020-08-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Keyword', '0002_video_videokeywordnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoViews',
            fields=[
                ('views', models.IntegerField()),
                ('check_time', models.DateTimeField()),
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'video_views',
                'managed': False,
            },
        ),
    ]
