# Generated by Django 3.0.8 on 2020-08-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search_Keyword', '0003_videoviews'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='videokeywordnew',
            table='video_keyword_new',
        ),
    ]
